// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: proto/car.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Car struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Brand         string                 `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Fuel          string                 `protobuf:"bytes,5,opt,name=fuel,proto3" json:"fuel,omitempty"`
	Seater        uint32                 `protobuf:"varint,6,opt,name=seater,proto3" json:"seater,omitempty"`
	Transmission  string                 `protobuf:"bytes,7,opt,name=transmission,proto3" json:"transmission,omitempty"`
	PricePerDay   uint32                 `protobuf:"varint,8,opt,name=pricePerDay,proto3" json:"pricePerDay,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Car) Reset() {
	*x = Car{}
	mi := &file_proto_car_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Car) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Car) ProtoMessage() {}

func (x *Car) ProtoReflect() protoreflect.Message {
	mi := &file_proto_car_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Car.ProtoReflect.Descriptor instead.
func (*Car) Descriptor() ([]byte, []int) {
	return file_proto_car_proto_rawDescGZIP(), []int{0}
}

func (x *Car) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Car) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Car) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Car) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Car) GetFuel() string {
	if x != nil {
		return x.Fuel
	}
	return ""
}

func (x *Car) GetSeater() uint32 {
	if x != nil {
		return x.Seater
	}
	return 0
}

func (x *Car) GetTransmission() string {
	if x != nil {
		return x.Transmission
	}
	return ""
}

func (x *Car) GetPricePerDay() uint32 {
	if x != nil {
		return x.PricePerDay
	}
	return 0
}

func (x *Car) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListCarsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	PickupTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=pickup_time,json=pickupTime,proto3" json:"pickup_time,omitempty"`
	ReturnTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=return_time,json=returnTime,proto3" json:"return_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCarsRequest) Reset() {
	*x = ListCarsRequest{}
	mi := &file_proto_car_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCarsRequest) ProtoMessage() {}

func (x *ListCarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_car_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCarsRequest.ProtoReflect.Descriptor instead.
func (*ListCarsRequest) Descriptor() ([]byte, []int) {
	return file_proto_car_proto_rawDescGZIP(), []int{1}
}

func (x *ListCarsRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *ListCarsRequest) GetPickupTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PickupTime
	}
	return nil
}

func (x *ListCarsRequest) GetReturnTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ReturnTime
	}
	return nil
}

type ListCarsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cars          []*Car                 `protobuf:"bytes,1,rep,name=cars,proto3" json:"cars,omitempty"`
	Brands        []string               `protobuf:"bytes,2,rep,name=brands,proto3" json:"brands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCarsResponse) Reset() {
	*x = ListCarsResponse{}
	mi := &file_proto_car_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCarsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCarsResponse) ProtoMessage() {}

func (x *ListCarsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_car_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCarsResponse.ProtoReflect.Descriptor instead.
func (*ListCarsResponse) Descriptor() ([]byte, []int) {
	return file_proto_car_proto_rawDescGZIP(), []int{2}
}

func (x *ListCarsResponse) GetCars() []*Car {
	if x != nil {
		return x.Cars
	}
	return nil
}

func (x *ListCarsResponse) GetBrands() []string {
	if x != nil {
		return x.Brands
	}
	return nil
}

type CreateBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CarId         uint32                 `protobuf:"varint,1,opt,name=carId,proto3" json:"carId,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Contact       string                 `protobuf:"bytes,3,opt,name=contact,proto3" json:"contact,omitempty"`
	License       string                 `protobuf:"bytes,4,opt,name=license,proto3" json:"license,omitempty"`
	Amount        float32                `protobuf:"fixed32,5,opt,name=amount,proto3" json:"amount,omitempty"`
	PickupTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=pickupTime,proto3" json:"pickupTime,omitempty"`
	ReturnTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=returnTime,proto3" json:"returnTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	mi := &file_proto_car_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_car_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_car_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBookingRequest) GetCarId() uint32 {
	if x != nil {
		return x.CarId
	}
	return 0
}

func (x *CreateBookingRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateBookingRequest) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *CreateBookingRequest) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *CreateBookingRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateBookingRequest) GetPickupTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PickupTime
	}
	return nil
}

func (x *CreateBookingRequest) GetReturnTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ReturnTime
	}
	return nil
}

type CreateBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingResponse) Reset() {
	*x = CreateBookingResponse{}
	mi := &file_proto_car_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingResponse) ProtoMessage() {}

func (x *CreateBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_car_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingResponse.ProtoReflect.Descriptor instead.
func (*CreateBookingResponse) Descriptor() ([]byte, []int) {
	return file_proto_car_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBookingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Pwd           string                 `protobuf:"bytes,4,opt,name=pwd,proto3" json:"pwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_car_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_car_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_car_proto_rawDescGZIP(), []int{5}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

type SignUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Pwd           string                 `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpRequest) Reset() {
	*x = SignUpRequest{}
	mi := &file_proto_car_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpRequest) ProtoMessage() {}

func (x *SignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_car_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpRequest.ProtoReflect.Descriptor instead.
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return file_proto_car_proto_rawDescGZIP(), []int{6}
}

func (x *SignUpRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignUpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignUpRequest) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

type SignUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpResponse) Reset() {
	*x = SignUpResponse{}
	mi := &file_proto_car_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpResponse) ProtoMessage() {}

func (x *SignUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_car_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpResponse.ProtoReflect.Descriptor instead.
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return file_proto_car_proto_rawDescGZIP(), []int{7}
}

func (x *SignUpResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SignUpResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Pwd           string                 `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_car_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_car_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_car_proto_rawDescGZIP(), []int{8}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_car_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_car_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_car_proto_rawDescGZIP(), []int{9}
}

func (x *LoginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_proto_car_proto protoreflect.FileDescriptor

const file_proto_car_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/car.proto\x12\x03car\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xeb\x01\n" +
	"\x03Car\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05brand\x18\x02 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\x12\n" +
	"\x04fuel\x18\x05 \x01(\tR\x04fuel\x12\x16\n" +
	"\x06seater\x18\x06 \x01(\rR\x06seater\x12\"\n" +
	"\ftransmission\x18\a \x01(\tR\ftransmission\x12 \n" +
	"\vpricePerDay\x18\b \x01(\rR\vpricePerDay\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\"\xa1\x01\n" +
	"\x0fListCarsRequest\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12;\n" +
	"\vpickup_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"pickupTime\x12;\n" +
	"\vreturn_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"returnTime\"H\n" +
	"\x10ListCarsResponse\x12\x1c\n" +
	"\x04cars\x18\x01 \x03(\v2\b.car.CarR\x04cars\x12\x16\n" +
	"\x06brands\x18\x02 \x03(\tR\x06brands\"\x88\x02\n" +
	"\x14CreateBookingRequest\x12\x14\n" +
	"\x05carId\x18\x01 \x01(\rR\x05carId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\rR\x06userId\x12\x18\n" +
	"\acontact\x18\x03 \x01(\tR\acontact\x12\x18\n" +
	"\alicense\x18\x04 \x01(\tR\alicense\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x02R\x06amount\x12:\n" +
	"\n" +
	"pickupTime\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"pickupTime\x12:\n" +
	"\n" +
	"returnTime\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"returnTime\"1\n" +
	"\x15CreateBookingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"R\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x10\n" +
	"\x03pwd\x18\x04 \x01(\tR\x03pwd\"K\n" +
	"\rSignUpRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x10\n" +
	"\x03pwd\x18\x03 \x01(\tR\x03pwd\"I\n" +
	"\x0eSignUpResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1d\n" +
	"\x04user\x18\x02 \x01(\v2\t.car.UserR\x04user\"6\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x10\n" +
	"\x03pwd\x18\x02 \x01(\tR\x03pwd\"b\n" +
	"\rLoginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\x04user\x18\x03 \x01(\v2\t.car.UserR\x04user2\xbc\x02\n" +
	"\n" +
	"CarService\x12F\n" +
	"\bListCars\x12\x14.car.ListCarsRequest\x1a\x15.car.ListCarsResponse\"\r\x82\xd3\xe4\x93\x02\a\x12\x05/cars\x12\\\n" +
	"\rCreateBooking\x12\x19.car.CreateBookingRequest\x1a\x1a.car.CreateBookingResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/bookings\x12E\n" +
	"\x06SignUp\x12\x12.car.SignUpRequest\x1a\x13.car.SignUpResponse\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/signup\x12A\n" +
	"\x05Login\x12\x11.car.LoginRequest\x1a\x12.car.LoginResponse\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/loginB\x0fZ\rbackend/protob\x06proto3"

var (
	file_proto_car_proto_rawDescOnce sync.Once
	file_proto_car_proto_rawDescData []byte
)

func file_proto_car_proto_rawDescGZIP() []byte {
	file_proto_car_proto_rawDescOnce.Do(func() {
		file_proto_car_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_car_proto_rawDesc), len(file_proto_car_proto_rawDesc)))
	})
	return file_proto_car_proto_rawDescData
}

var file_proto_car_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_car_proto_goTypes = []any{
	(*Car)(nil),                   // 0: car.Car
	(*ListCarsRequest)(nil),       // 1: car.ListCarsRequest
	(*ListCarsResponse)(nil),      // 2: car.ListCarsResponse
	(*CreateBookingRequest)(nil),  // 3: car.CreateBookingRequest
	(*CreateBookingResponse)(nil), // 4: car.CreateBookingResponse
	(*User)(nil),                  // 5: car.User
	(*SignUpRequest)(nil),         // 6: car.SignUpRequest
	(*SignUpResponse)(nil),        // 7: car.SignUpResponse
	(*LoginRequest)(nil),          // 8: car.LoginRequest
	(*LoginResponse)(nil),         // 9: car.LoginResponse
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_proto_car_proto_depIdxs = []int32{
	10, // 0: car.ListCarsRequest.pickup_time:type_name -> google.protobuf.Timestamp
	10, // 1: car.ListCarsRequest.return_time:type_name -> google.protobuf.Timestamp
	0,  // 2: car.ListCarsResponse.cars:type_name -> car.Car
	10, // 3: car.CreateBookingRequest.pickupTime:type_name -> google.protobuf.Timestamp
	10, // 4: car.CreateBookingRequest.returnTime:type_name -> google.protobuf.Timestamp
	5,  // 5: car.SignUpResponse.user:type_name -> car.User
	5,  // 6: car.LoginResponse.user:type_name -> car.User
	1,  // 7: car.CarService.ListCars:input_type -> car.ListCarsRequest
	3,  // 8: car.CarService.CreateBooking:input_type -> car.CreateBookingRequest
	6,  // 9: car.CarService.SignUp:input_type -> car.SignUpRequest
	8,  // 10: car.CarService.Login:input_type -> car.LoginRequest
	2,  // 11: car.CarService.ListCars:output_type -> car.ListCarsResponse
	4,  // 12: car.CarService.CreateBooking:output_type -> car.CreateBookingResponse
	7,  // 13: car.CarService.SignUp:output_type -> car.SignUpResponse
	9,  // 14: car.CarService.Login:output_type -> car.LoginResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_car_proto_init() }
func file_proto_car_proto_init() {
	if File_proto_car_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_car_proto_rawDesc), len(file_proto_car_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_car_proto_goTypes,
		DependencyIndexes: file_proto_car_proto_depIdxs,
		MessageInfos:      file_proto_car_proto_msgTypes,
	}.Build()
	File_proto_car_proto = out.File
	file_proto_car_proto_goTypes = nil
	file_proto_car_proto_depIdxs = nil
}
